constexpr uint32_t NUM_BITS_IN_FIELD = 254;
constexpr uint32_t SPLIT_THREADS = 1024;
constexpr uint32_t BUCKET_THREADS = 256;
constexpr uint32_t CHUNKED_REDUCTION_THREADS = 128;
constexpr uint32_t CHUNKED_REDUCTION_CHUNK_SIZE = 2048;
constexpr int LARGE_BUCKET_MIN_THRESHOLD =
    static_cast<int>(GPU_MSM_LARGE_BUCKET_MIN_THRESHOLD);
constexpr uint32_t DEFAULT_SCALAR_SPLIT_FIRST_CHUNK_PERCENT = 87;
constexpr uint32_t DEFAULT_LARGE_BUCKET_CHUNK_SIZE = 256;
constexpr int LARGE_BUCKET_TREE_REDUCTION_MIN_CHUNKS = 17;

constexpr size_t BUCKET_STAT_NORMAL_JOBS = 0;
constexpr size_t BUCKET_STAT_LARGE_JOBS = 1;
constexpr size_t BUCKET_STAT_NORMAL_POINTS = 2;
constexpr size_t BUCKET_STAT_LARGE_POINTS = 3;
constexpr size_t BUCKET_STAT_MAX_SIZE = 4;
constexpr size_t BUCKET_STAT_LARGE_CHUNKS = 5;
constexpr size_t BUCKET_STAT_LARGE_FULL_CHUNKS = 6;
constexpr size_t BUCKET_STAT_HISTOGRAM_START = 7;
constexpr size_t BUCKET_STAT_COUNT =
    BUCKET_STAT_HISTOGRAM_START + MSM_BUCKET_HISTOGRAM_BINS;
